#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
HISTORY_FILE="$SCRIPT_DIR/.ship-history"

# ── Colors ──
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BOLD='\033[1m'
NC='\033[0m'

info()  { echo -e "${BOLD}▸${NC} $1"; }
ok()    { echo -e "${GREEN}✓${NC} $1"; }
err()   { echo -e "${RED}✗${NC} $1" >&2; }

# ── 1. Read last version ──
if [[ -f "$HISTORY_FILE" ]]; then
  LAST_VERSION="$(tail -1 "$HISTORY_FILE")"
else
  LAST_VERSION="0.0.0"
fi

echo ""
echo -e "${BOLD}Last shipped version: ${YELLOW}${LAST_VERSION}${NC}"
echo ""

# ── 2. Prompt for new version ──
read -rp "Enter new version (must be higher than ${LAST_VERSION}): " VERSION

# Validate semver format
if ! [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  err "Invalid version format. Must be X.Y.Z (e.g. 1.2.0)"
  exit 1
fi

# Compare versions - new must be strictly higher
HIGHEST="$(printf '%s\n%s' "$LAST_VERSION" "$VERSION" | sort -V | tail -1)"
if [[ "$VERSION" == "$LAST_VERSION" ]] || [[ "$HIGHEST" != "$VERSION" ]]; then
  err "Version $VERSION is not higher than $LAST_VERSION"
  exit 1
fi

# ── 3. Prompt for platforms ──
echo ""
echo "Which platforms to ship?"
echo "  1) Desktop (macOS, Windows, Linux)"
echo "  2) iOS (EAS Build → App Store)"
echo "  3) Android (EAS Build → Google Play)"
echo "  4) All"
echo ""
read -rp "Select (comma-separated, e.g. 1,2): " PLATFORM_INPUT

SHIP_DESKTOP=false
SHIP_IOS=false
SHIP_ANDROID=false

IFS=',' read -ra SELECTIONS <<< "$PLATFORM_INPUT"
for sel in "${SELECTIONS[@]}"; do
  sel="$(echo "$sel" | tr -d ' ')"
  case "$sel" in
    1) SHIP_DESKTOP=true ;;
    2) SHIP_IOS=true ;;
    3) SHIP_ANDROID=true ;;
    4) SHIP_DESKTOP=true; SHIP_IOS=true; SHIP_ANDROID=true ;;
    *) err "Invalid selection: $sel"; exit 1 ;;
  esac
done

if ! $SHIP_DESKTOP && ! $SHIP_IOS && ! $SHIP_ANDROID; then
  err "No platforms selected"
  exit 1
fi

# Build platform label and tags
PLATFORMS=()
TAGS=()
$SHIP_DESKTOP && PLATFORMS+=("desktop") && TAGS+=("desktop/v${VERSION}")
$SHIP_IOS     && PLATFORMS+=("ios")     && TAGS+=("ios/v${VERSION}")
$SHIP_ANDROID && PLATFORMS+=("android") && TAGS+=("android/v${VERSION}")
PLATFORM_LABEL="$(IFS=', '; echo "${PLATFORMS[*]}")"

echo ""
info "Shipping v${VERSION} for: ${PLATFORM_LABEL}"
echo ""

# ── 4. Bump version in all 4 files ──
# Always bump ALL files to keep versions in sync
# Note: ios/Info.plist is gitignored (generated by Expo) — EAS reads version from app.json

# src/app/app.json - "version": "X.Y.Z"
sed -i '' 's/"version": "[0-9]*\.[0-9]*\.[0-9]*"/"version": "'"$VERSION"'"/' \
  "$SCRIPT_DIR/src/app/app.json"

# src/desktop/src-tauri/tauri.conf.json - "version": "X.Y.Z"
sed -i '' 's/"version": "[0-9]*\.[0-9]*\.[0-9]*"/"version": "'"$VERSION"'"/' \
  "$SCRIPT_DIR/src/desktop/src-tauri/tauri.conf.json"

# src/desktop/package.json - "version": "X.Y.Z"
sed -i '' 's/"version": "[0-9]*\.[0-9]*\.[0-9]*"/"version": "'"$VERSION"'"/' \
  "$SCRIPT_DIR/src/desktop/package.json"

# src/desktop/src-tauri/Cargo.toml - version = "X.Y.Z"
sed -i '' 's/^version = "[0-9]*\.[0-9]*\.[0-9]*"/version = "'"$VERSION"'"/' \
  "$SCRIPT_DIR/src/desktop/src-tauri/Cargo.toml"

ok "Version bumped to ${VERSION} in 4 files"

# ── 5. Git commit, tag, push ──
git -C "$SCRIPT_DIR" add \
  src/app/app.json \
  src/desktop/src-tauri/tauri.conf.json \
  src/desktop/package.json \
  src/desktop/src-tauri/Cargo.toml

git -C "$SCRIPT_DIR" commit -m "Release v${VERSION} (${PLATFORM_LABEL})"

for tag in "${TAGS[@]}"; do
  git -C "$SCRIPT_DIR" tag "$tag"
done

git -C "$SCRIPT_DIR" push
git -C "$SCRIPT_DIR" push origin "${TAGS[@]}"

ok "Pushed v${VERSION} — CI will build: ${PLATFORM_LABEL}"

# ── 6. Record version ──
echo "$VERSION" >> "$HISTORY_FILE"

echo ""
echo "  Monitor: https://github.com/radaiko/SnackPilot/actions"
echo ""
